[tool.poetry]
name = "helios pipeline"
version = "1.0.0"
description = "A growing pipeline to eat the public cloud"
authors = ["Alec Di Vito <divito.alec@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.1"
